<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>  
    <RootNamespace>BlazorShared</RootNamespace>
    <AssemblyName>BlazorShared</AssemblyName>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BlazorInputFile" />
    <PackageReference Include="FluentValidation" />
  </ItemGroup>

</Project>
